// Automatically generated by mockimpl. DO NOT EDIT!

package mock

import (
	"context"
	"io"
	"sync"

	"github.com:it-laborato/MDM_Lab/server/mdmlab"
)

var _ mdmlab.InstallerStore = (*InstallerStore)(nil)

type GetFunc func(ctx context.Context, installer mdmlab.Installer) (io.ReadCloser, int64, error)

type PutFunc func(ctx context.Context, installer mdmlab.Installer) (string, error)

type ExistsFunc func(ctx context.Context, installer mdmlab.Installer) (bool, error)

type InstallerStore struct {
	GetFunc        GetFunc
	GetFuncInvoked bool

	PutFunc        PutFunc
	PutFuncInvoked bool

	ExistsFunc        ExistsFunc
	ExistsFuncInvoked bool

	mu sync.Mutex
}

func (s *InstallerStore) Get(ctx context.Context, installer mdmlab.Installer) (io.ReadCloser, int64, error) {
	s.mu.Lock()
	s.GetFuncInvoked = true
	s.mu.Unlock()
	return s.GetFunc(ctx, installer)
}

func (s *InstallerStore) Put(ctx context.Context, installer mdmlab.Installer) (string, error) {
	s.mu.Lock()
	s.PutFuncInvoked = true
	s.mu.Unlock()
	return s.PutFunc(ctx, installer)
}

func (s *InstallerStore) Exists(ctx context.Context, installer mdmlab.Installer) (bool, error) {
	s.mu.Lock()
	s.ExistsFuncInvoked = true
	s.mu.Unlock()
	return s.ExistsFunc(ctx, installer)
}
